/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { UnlimitedOcrMode } from './unlimitedOcrMode';

export interface PipelineConfigPatch {
  /** @nullable */
  bubbleSegmenter?: string | null;
  /** @nullable */
  comicTextBubbleDetectorClasses?: string[] | null;
  /** @nullable */
  detector?: string | null;
  /**
     * `Some(Some(x))` sets an override, `Some(None)` clears it back to the
     * detector's built-in default, `None` leaves the existing value as-is.
     * @nullable
     */
  detectorConfidenceThreshold?: number | null;
  /** @nullable */
  fontDetector?: string | null;
  /** @nullable */
  inpainter?: string | null;
  /** @nullable */
  ocr?: string | null;
  /** @nullable */
  renderer?: string | null;
  /** @nullable */
  segmenter?: string | null;
  /**
     * `Some(Some(x))` sets an override, `Some(None)` clears it back to the
     * segmenter's built-in default, `None` leaves the existing value as-is.
     * @nullable
     */
  segmenterBinaryThreshold?: number | null;
  /** @nullable */
  translator?: string | null;
  unlimitedOcrMode?: null | UnlimitedOcrMode;
  /** @nullable */
  unlimitedOcrUrl?: string | null;
  anytext2Url?: string;
}
