/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { UnlimitedOcrMode } from './unlimitedOcrMode';

/**
 * Engine selection for each pipeline stage.
 * Values are engine IDs (e.g. "pp-doclayout-v3", "comic-text-detector").
 * Empty string means use default.
 */
export interface PipelineConfig {
  bubble_segmenter?: string;
  detector?: string;
  font_detector?: string;
  inpainter?: string;
  ocr?: string;
  renderer?: string;
  segmenter?: string;
  translator?: string;
  unlimited_ocr_mode?: UnlimitedOcrMode;
  /** @nullable */
  unlimited_ocr_url?: string | null;
}
