/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface ProviderPatch {
  /**
     * `"[REDACTED]"` → keep existing keyring secret; empty → clear; otherwise save.
     * @nullable
     */
  apiKey?: string | null;
  /**
     * `None` = unchanged. `Some(None)` = clear. `Some(Some(x))` = set.
     * @nullable
     */
  baseUrl?: string | null;
  id: string;
  /**
     * `None` = unchanged. `Some(None)` = clear. `Some(Some(x))` = set.
     * @minimum 0
     * @nullable
     */
  maxTokens?: number | null;
  /**
     * `None` = unchanged. `Some(None)` = clear. `Some(Some(x))` = set.
     * @nullable
     */
  model?: string | null;
  /**
     * `None` = unchanged. `Some(None)` = clear. `Some(Some(x))` = set.
     * @nullable
     */
  temperature?: number | null;
}
