/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface ProviderConfig {
  /**
     * Populated from credential storage on `load()`, never written to config.toml.
     * Serializes as `"[REDACTED]"` in API responses.
     * @nullable
     */
  api_key?: string | null;
  /** @nullable */
  base_url?: string | null;
  id: string;
  /**
     * @minimum 0
     * @nullable
     */
  max_tokens?: number | null;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  temperature?: number | null;
}
