/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface TextTranslationContext {
  /** True when context was inferred with low certainty. */
  contextUncertain?: boolean;
  /**
     * Soft hint only.
     * @nullable
     */
  emotionHint?: string | null;
  /**
     * dialogue / narration / sfx / sign / unknown
     * @nullable
     */
  role?: string | null;
  /**
     * Soft hint only — not guaranteed.
     * @nullable
     */
  speakerHint?: string | null;
  /**
     * Note for translation model.
     * @nullable
     */
  translationNote?: string | null;
  /**
     * Visual context around the text box.
     * @nullable
     */
  visualHint?: string | null;
}
