/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * Controls how the pipeline handles unlimited-OCR routing.
 */
export type UnlimitedOcrMode = typeof UnlimitedOcrMode[keyof typeof UnlimitedOcrMode];


export const UnlimitedOcrMode = {
  off: 'off',
  full: 'full',
  'smart-fallback': 'smart-fallback',
} as const;
